artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/winequality-red.csv
  download_dir: artifacts/data_ingestion/winequality-red.csv